esp32:
  board: nodemcu-32s
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "aafqv2q+T92WCNL3AYvuDT2GDO1KA/7l6iyrpG/wKN4="
  custom_services: true  # Required for chirp component services

ota:
  - platform: esphome
    password: "7d7451136004083acd6be5cc9d24efe0"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Plantsensor-Jer Fallback Hotspot"
    password: "q0q7u9b7E3XH"

captive_portal:

esphome:
  name: plantsensor-jer
  friendly_name: plantsensor-jer

# Chirp I2C Soil Moisture Sensor Configuration
# Based on: https://wemakethings.net/chirp/
# 
# The custom chirp component automatically:
# - Scans I2C bus for Chirp sensors (default address 0x20, or custom like 0x6F)
# - Creates sensors for each device found (moisture, temperature, light)
# - Handles address changes via Home Assistant service
# - Supports custom labeling via Home Assistant service
#
# Calibration values used (from original config):
# - Dry air: 263
# - Water: 483
# 
# Home Assistant Services:
# - esphome.plantsensor_jer_set_address: Change I2C address of a device
#   Parameters: old_address (hex), new_address (hex)
# - esphome.plantsensor_jer_set_label: Set friendly label for a device
#   Parameters: address (hex), label (string)
# - esphome.plantsensor_jer_rescan: Force rescan of I2C bus

# Load the custom chirp component from local components folder
external_components:
  - source:
      type: local
      path: components

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true

# Chirp I2C Soil Moisture Sensors
# Add new sensors by defining additional platform: chirp entries
sensor:
  - platform: chirp
    address: 0x20
    device_name: "Plant 1"
    update_interval: 60s
    moisture:
      name: "Plant 1 Soil Moisture"
    temperature:
      name: "Plant 1 Soil Temperature"
    light:
      name: "Plant 1 Soil Light"
      
  - platform: chirp
    address: 0x6F
    device_name: "Plant 2"
    update_interval: 60s
    moisture:
      name: "Plant 2 Soil Moisture"
    temperature:
      name: "Plant 2 Soil Temperature"
    light:
      name: "Plant 2 Soil Light"


